
(custom-set-faces
 '(gams-comment-face ((t (:foreground "#009000"))))
 '(gams-mpsge-face ((t (:foreground "#2080e0"))))
 '(gams-statement-face ((t (:foreground "#0000e0"))))
 '(gams-dollar-face ((t (:foreground "dark orange"))))
 '(gams-string-face ((t (:foreground "#a000a0"))))
 '(gams-operator-face ((t (:foreground "#e00000"))))
 '(gams-slash-face ((t (:foreground "#f00090"))))
 '(gams-explanation-face ((t (:foreground "#c09000"))))
 '(gams-oth-cont-face ((t (:foreground "gray50"))))
 '(gams-title-face ((t ( :foreground "#0000a0" :background "#e8e8a5"))))
 '(gams-highline-face ((t (:foreground "#202020" :background "PaleGreen1"))))
 '(gams-lst-par-face ((t (:bold t :foreground "DodgerBlue"))))
 '(gams-lst-set-face ((t (:bold t :foreground "#d06000"))))
 '(gams-lst-var-face ((t (:bold t :foreground "hot pink"))))
 '(gams-lst-equ-face ((t (:bold t :foreground "lime green"))))
 '(gams-lst-vri-face ((t (:bold t :foreground "purple"))))
 '(gams-lst-oth-face ((t (:bold t :foreground "gray60"))))
 '(gams-lst-warning-face ((t (:bold t :foreground "red"))))
 '(gams-warning-face ((t (:bold t :foreground "red"))))
 '(gams-lst-program-face ((t (:foreground "goldenrod"))))
 '(gams-ol-loo-face ((t (:bold t :foreground "maroon"))))
 '(gams-highline-sub-face ((t (:foreground "#202020" :background "misty rose"))))
 '(gams-sil-mpsge-face ((t (:foreground "#2080e0"))))
 '(gams-sil-dollar-face ((t (:foreground "dark orange"))))
 '(gams-sil-file-face ((t (:foreground "#800060" :background "#f0dada"))))
 '(gams-sil-file-face-2 ((t (:foreground "#800060" :background "#dadada"))))
 '(gams-func-face ((t (:foreground "pink"))))
 '(gams-def-face ((t (:bold t :foreground "blue"))))
 '(gams-highlighted-keywords-face ((t (:bold t :foreground "red"))))
 '(gams-sid-highline-face ((t (:foreground "#202020" :background "PaleGreen1"))))
 '(gams-lxi-col-face ((t (:bold t :foreground "lime green"))))
 '(gams-lxi-equ-face ((t (:bold t :foreground "orange"))))
 '(gams-level-face-1 ((t (:bold t :foreground "Blue1"))))
 '(gams-level-face-2 ((t (:bold t :foreground "DarkGoldenrod"))))
 '(gams-level-face-3 ((t (:bold t :foreground "Purple"))))
 '(gams-level-face-4 ((t (:bold t :foreground "Firebrick"))))
 '(gams-level-face-5 ((t (:foreground "ForestGreen"))))
 '(gams-level-face-6 ((t (:foreground "CadetBlue"))))
 '(gams-level-face-7 ((t (:foreground "Orchid"))))
 '(gams-level-face-8 ((t (:foreground "RosyBrown"))))
 )

(custom-set-faces
 '(gams-comment-face ((t (:foreground "green"))))
 '(gams-mpsge-face ((t (:foreground "hot pink"))))
 '(gams-statement-face ((t (:foreground "cyan"))))
 '(gams-dollar-face ((t (:foreground "yellow"))))
 '(gams-string-face ((t (:foreground "orange"))))
 '(gams-operator-face ((t (:foreground "#ccaaff"))))
 '(gams-slash-face ((t (:foreground "light pink"))))
 '(gams-explanation-face ((t (:foreground "khaki"))))
 '(gams-oth-cont-face ((t (:foreground "khaki"))))
 '(gams-title-face ((t ( :foreground "#ffd0ff"))))
 '(gams-highline-face ((t (:bold t :underline t :foreground "yellow"))))
 '(gams-lst-par-face ((t (:bold t :foreground "yellow"))))
 '(gams-lst-set-face ((t (:bold t :foreground "sandy brown"))))
 '(gams-lst-var-face ((t (:bold t :foreground "cyan"))))
 '(gams-lst-equ-face ((t (:bold t :foreground "pink"))))
 '(gams-lst-vri-face ((t (:bold t :foreground "pale green"))))
 '(gams-lst-oth-face ((t (:bold t :foreground "bisque"))))
 '(gams-lst-warning-face ((t (:bold t :foreground "red"))))
 '(gams-warning-face ((t (:bold t :foreground "red"))))
 '(gams-lst-program-face ((t (:foreground "khaki"))))
 '(gams-ol-loo-face ((t (:bold t :foreground "#7777ff"))))
 '(gams-highline-sub-face ((t (:bold t :underline t :foreground "pink"))))
 '(gams-sil-mpsge-face ((t (:foreground "hot pink"))))
 '(gams-sil-dollar-face ((t (:foreground "#ffa0ff"))))
 '(gams-sil-file-face ((t (:foreground "#ff7070"))))
 '(gams-sil-file-face-2 ((t (:foreground "#c0c0c0"))))
 '(gams-func-face ((t (:foreground "#ff30ff"))))
 '(gams-def-face ((t (:bold t :foreground "white"))))
 '(gams-highlighted-keywords-face ((t (:bold t :foreground "yellow"))))
 '(gams-sid-highline-face ((t (:foreground "white" :background "#008000"))))
 '(gams-lxi-col-face ((t (:bold t :foreground "green"))))
 '(gams-lxi-equ-face ((t (:bold t :foreground "orange"))))
 '(gams-level-face-1 ((t (:bold t :foreground "LightSkyBlue"))))
 '(gams-level-face-2 ((t (:bold t :foreground "LightGoldenrod"))))
 '(gams-level-face-3 ((t (:bold t :foreground "Cyan1"))))
 '(gams-level-face-4 ((t (:bodl t :foreground "chocolate1"))))
 '(gams-level-face-5 ((t (:foreground "PaleGreen"))))
 '(gams-level-face-6 ((t (:foreground "Aquamarine"))))
 '(gams-level-face-7 ((t (:foreground "LightSteelBlue"))))
 '(gams-level-face-8 ((t (:foreground "LightSalmon"))))
 )






